apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-service
spec:
  selector:
    app: two-tier-app
  ports:
    - protocol: TCP
      port: 80             #port used to access the service within the cluster / internal access . 
      targetPort: 5000     #Pods port , Target pods with this port number
      nodePort: 30004      # is only used when exposing the service to external traffic and designates the port on the nodes for external access.
  type: NodePort
