apiVersion: v1
kind: Pod
metadata:
  name: two-tier-app-pod
spec:
  containers:
  - name: two-tier-app-pod
    image: spyder12/flaskapp:latest
    env:
      - name: MYSQL_HOST
        value: "mysql"          # this is your mysql's/pod  service clusture IP, Make sure to change it with yours
      - name: MYSQL_PASSWORD
        value: "admin"
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_DB
        value: "mydb"
    ports:
      - containerPort: 5000
    imagePullPolicy: Always          # "Always" means it will always attempt to pull the latest version of the image.
   
